import { AspectRatioOption, CameraMovementOption, PromptFormState } from './types';

export const ASPECT_RATIOS: AspectRatioOption[] = [
  { value: "16:9", label: "16:9 (Widescreen)" },
  { value: "1:1", label: "1:1 (Square)" },
  { value: "9:16", label: "9:16 (Portrait)" },
  { value: "4:3", label: "4:3 (Standard)" },
  { value: "3:2", label: "3:2 (Photography)" },
  { value: "21:9", label: "21:9 (Cinematic)" },
];

export const CAMERA_MOVEMENTS: CameraMovementOption[] = [
  { value: "", label_id: "Pilih Gerakan Kamera...", label_en: "Select Camera Movement..." },
  { value: "static", label_id: "Static (Diam)", label_en: "Static" },
  { value: "pan_left", label_id: "Pan Left (Geser Kiri)", label_en: "Pan Left" },
  { value: "pan_right", label_id: "Pan Right (Geser Kanan)", label_en: "Pan Right" },
  { value: "tilt_up", label_id: "Tilt Up (Miring ke Atas)", label_en: "Tilt Up" },
  { value: "tilt_down", label_id: "Tilt Down (Miring ke Bawah)", label_en: "Tilt Down" },
  { value: "zoom_in", label_id: "Zoom In (Perbesar)", label_en: "Zoom In" },
  { value: "zoom_out", label_id: "Zoom Out (Perkecil)", label_en: "Zoom Out" },
  { value: "dolly_in", label_id: "Dolly In (Maju)", label_en: "Dolly In" },
  { value: "dolly_out", label_id: "Dolly Out (Mundur)", label_en: "Dolly Out" },
  { value: "truck_left", label_id: "Truck Left (Geser Kiri - Dolly)", label_en: "Truck Left" },
  { value: "truck_right", label_id: "Truck Right (Geser Kanan - Dolly)", label_en: "Truck Right" },
  { value: "pedestal_up", label_id: "Pedestal Up (Naik)", label_en: "Pedestal Up" },
  { value: "pedestal_down", label_id: "Pedestal Down (Turun)", label_en: "Pedestal Down" },
  { value: "tracking_shot", label_id: "Tracking Shot (Mengikuti Objek)", label_en: "Tracking Shot" },
  { value: "crane_shot", label_id: "Crane Shot (Tembakan Derek)", label_en: "Crane Shot" },
  { value: "handheld", label_id: "Handheld (Genggam Tangan)", label_en: "Handheld" },
  { value: "steadicam", label_id: "Steadicam", label_en: "Steadicam" },
  { value: "drone_shot", label_id: "Drone Shot (Tembakan Drone)", label_en: "Drone Shot" },
  { value: "aerial_shot", label_id: "Aerial Shot (Tembakan Udara)", label_en: "Aerial Shot" },
  { value: "birds_eye_view", label_id: "Bird's Eye View (Pandangan Mata Burung)", label_en: "Bird's Eye View" },
  { value: "worms_eye_view", label_id: "Worm's Eye View (Pandangan Mata Cacing)", label_en: "Worm's Eye View" },
  { value: "arc_shot", label_id: "Arc Shot (Tembakan Melengkung)", label_en: "Arc Shot" },
  { value: "orbit_shot", label_id: "Orbit Shot (Tembakan Mengorbit)", label_en: "Orbit Shot" },
  { value: "roll", label_id: "Roll (Bergulir)", label_en: "Roll" },
  { value: "dutch_angle", label_id: "Dutch Angle/Tilt (Sudut Belanda)", label_en: "Dutch Angle/Tilt" },
  { value: "whip_pan", label_id: "Whip Pan (Geser Cepat)", label_en: "Whip Pan" },
  { value: "crash_zoom", label_id: "Crash Zoom (Zoom Cepat)", label_en: "Crash Zoom" },
  { value: "push_in", label_id: "Push In (Dorong Masuk)", label_en: "Push In" },
  { value: "pull_out", label_id: "Pull Out (Tarik Keluar)", label_en: "Pull Out" },
  { value: "reveal_shot", label_id: "Reveal Shot (Tembakan Pengungkapan)", label_en: "Reveal Shot" },
  { value: "3d_rotation", label_id: "3D Rotation (Rotasi 3D)", label_en: "3D Rotation" },
  { value: "point_of_view", label_id: "Point of View (POV) (Sudut Pandang Karakter)", label_en: "Point of View (POV)"},
];

export const INITIAL_FORM_STATE: PromptFormState = {
  sceneTitle: "",
  characterCoreDescription: "",
  characterVoiceDetails: "",
  characterAction: "",
  characterExpression: "",
  sceneLocationTime: "",
  additionalVisualDetails: "",
  cameraMovement: CAMERA_MOVEMENTS[0].value,
  overallAtmosphere: "",
  environmentalSounds: "",
  characterDialog: "",
  aspectRatio: ASPECT_RATIOS[0].value,
  negativePrompt: "",
};
